# -*- coding: utf-8 -*-
"""Training1DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18lV4qEssylj5QlDPhCEgvZDSpmSxikkg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
data=load_iris()
df=pd.DataFrame(data.data,columns=data.feature_names)
print("Mean :")
print(df.mean())
print("standard Deviation :")
print(df.std())
print("Mode :")
print(df.mode())
print("Median :")
print(df.median())
print("variance :")
print(df.var())
print("correlation :")
print(df.corr())
sns.boxplot(x='sepal length (cm)', y='sepal width (cm)', data=df)
plt.title('Box Plot of Sepal Length vs. Sepal Width')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.grid(False)
plt.show()